In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
datasets=pd.read_csv("/content/Product_purchase (1).csv")
#importing datasets
x=datasets.iloc[:,[2,3]].values
y=datasets.iloc[:,4].values
print(x)
print(y)
print(datasets.columns[[2,3]])
print(datasets.columns[4])

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [ ]:
#splitting dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [ ]:
#decision tree
# create decision tree classifier object
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,min_samples_split=5,min_samples_leaf=2)

model.fit(x_train,y_train) #training the model
print(model)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)


In [ ]:
y_pred_dec=model.predict(x_test)   #predict the testing model OR testing the model

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix #making confusion matrix
cm=confusion_matrix(y_test,y_pred_dec)
cm

array([[64,  4],
       [ 6, 26]])

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_dec))

0.9


In [ ]:
#create an object of algorithm/model
from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression(random_state=0)
modellr.fit(x_train,y_train)
y_pred_dec=modellr.predict(x_test)   #predict the testing model
y_pred_dec

from sklearn.metrics import confusion_matrix #making confusion matrix
cmlr=confusion_matrix(y_test,y_pred_dec)
cmlr

from sklearn.metrics import accuracy_score
print("LogisticRegression",accuracy_score(y_test,y_pred_dec))


LogisticRegression 0.89


In [ ]:
#fitting the classifier into training set
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion="entropy",random_state=0)
RFmodel.fit(x_train,y_train)
print(RFmodel)

#predict thwe test set results
y_pred_rf=RFmodel.predict(x_test)
y_pred_rf

from sklearn.metrics import confusion_matrix  #making the confusion matrix
cmrf=confusion_matrix(y_test,y_pred_rf)
cmrf
from sklearn.metrics import accuracy_score
print("RandomForestClassifier",accuracy_score(y_test,y_pred_rf))

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)
RandomForestClassifier 0.92
